[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--version" # prevent npm version issues

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers for pages only, not static assets
[[headers]]
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]  
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Let Next.js handle routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat" 
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200